import localFont from "next/font/local";
import "./globals.css";
import Header from "./pages/header";
import Head from 'next/head';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Alveo Land",
  description: "Generated by create next app",
};

// No TypeScript interface, but PropTypes can be used for prop validation
const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} overflow-x-hidden` }>
    
        {children}
      </body>
    </html>
  );
};

// If you want to use PropTypes for validation:


export default RootLayout;
